name: Update Crypto Data

on:
  schedule:
    # 매 5분마다 실행
    - cron: '*/5 * * * *'
  workflow_dispatch: # 수동 실행 가능

jobs:
  update-crypto-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm init -y
        npm install node-fetch
        
    - name: Fetch crypto data
      run: |
        cat > fetch-crypto.js << 'EOF'
        const fetch = require('node-fetch');
        const fs = require('fs');
        
        async function fetchCryptoData() {
          try {
            console.log('Fetching crypto data...');
            
            // CoinGecko API 호출
            const globalResponse = await fetch(
              'https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum,ripple,cardano,solana&vs_currencies=usd&include_24hr_change=true'
            );
            const globalData = await globalResponse.json();
            
            // Upbit API 호출
            const upbitResponse = await fetch(
              'https://api.upbit.com/v1/ticker?markets=KRW-BTC,KRW-ETH,KRW-XRP,KRW-ADA,KRW-SOL'
            );
            const upbitData = await upbitResponse.json();
            
            // 환율 API 호출
            const exchangeResponse = await fetch(
              'https://api.exchangerate-api.com/v4/latest/USD'
            );
            const exchangeData = await exchangeResponse.json();
            const exchangeRate = exchangeData.rates.KRW;
            
            // 데이터 처리
            const coinMapping = {
              'bitcoin': { upbit: 'KRW-BTC', name: 'Bitcoin', symbol: 'BTC' },
              'ethereum': { upbit: 'KRW-ETH', name: 'Ethereum', symbol: 'ETH' },
              'ripple': { upbit: 'KRW-XRP', name: 'XRP', symbol: 'XRP' },
              'cardano': { upbit: 'KRW-ADA', name: 'Cardano', symbol: 'ADA' },
              'solana': { upbit: 'KRW-SOL', name: 'Solana', symbol: 'SOL' }
            };
            
            const coins = Object.entries(coinMapping).map(([coinId, info]) => {
              const globalPrice = globalData[coinId];
              const upbitPrice = upbitData.find(item => item.market === info.upbit);
              
              if (!globalPrice || !upbitPrice) return null;
              
              const globalPriceKRW = globalPrice.usd * exchangeRate;
              const upbitPriceKRW = upbitPrice.trade_price;
              const kimchiPremium = ((upbitPriceKRW - globalPriceKRW) / globalPriceKRW) * 100;
              
              return {
                coin: `${info.name} (${info.symbol})`,
                global_price: globalPriceKRW,
                upbit_price: upbitPriceKRW,
                kimchi_premium: kimchiPremium,
                change_24h: globalPrice.usd_24h_change,
                raw: {
                  global: globalPrice,
                  upbit: upbitPrice,
                  exchange_rate: exchangeRate
                }
              };
            }).filter(Boolean);
            
            // JSON 파일로 저장
            const result = {
              updated_at: new Date().toISOString(),
              coins: coins
            };
            
            fs.writeFileSync('data/crypto.json', JSON.stringify(result, null, 2));
            console.log('Crypto data updated successfully!');
            
          } catch (error) {
            console.error('Error fetching crypto data:', error);
            process.exit(1);
          }
        }
        
        fetchCryptoData();
        EOF
        
        mkdir -p data
        node fetch-crypto.js
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/crypto.json
        git diff --staged --quiet || git commit -m "Update crypto data - $(date)"
        git push